# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

# source 'https://cdn.cocoapods.org/'
target '2cents' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RNFBAnalytics', :path => '../node_modules/@react-native-firebase/analytics'

  # Pods for 2cents

end
